### Network Parameters
### Standard
# network_config: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml
# pretrained_weights: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml

### Light-weight
network_config: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
pretrained_weights: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
